"""database added

Revision ID: c7ee468d229c
Revises: 10c24c0ff1ab
Create Date: 2023-03-20 07:34:11.036863

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c7ee468d229c'
down_revision = '10c24c0ff1ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'university_id')
    op.drop_column('user', 'university')
    op.drop_column('user', 'university_school')
    op.drop_column('user', 'university_year_id')
    op.drop_column('user', 'university_year')
    op.drop_column('user', 'university_school_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('university_school_id', mysql.VARCHAR(length=20), nullable=False))
    op.add_column('user', sa.Column('university_year', mysql.VARCHAR(length=20), nullable=True))
    op.add_column('user', sa.Column('university_year_id', mysql.VARCHAR(length=20), nullable=False))
    op.add_column('user', sa.Column('university_school', mysql.VARCHAR(length=20), nullable=True))
    op.add_column('user', sa.Column('university', mysql.VARCHAR(length=20), nullable=True))
    op.add_column('user', sa.Column('university_id', mysql.VARCHAR(length=20), nullable=False))
    # ### end Alembic commands ###
