version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/sf_dissertation
# hooks:
#   BeforeInstall:
#     - location: scripts/install_dependencies.sh
#       timeout: 300
#       runas: root
#   AfterInstall:
#     - location: scripts/change_permissions.sh
#       timeout: 300
#       runas: root
#   ApplicationStart:
#     - location: scripts/start_server.sh
#     - location: scripts/create_test_db.sh
#       timeout: 300
#       runas: root
#   ApplicationStop:
#     - location: scripts/stop_server.sh
#       timeout: 300
#       runas: root

# reference: https://docs.aws.amazon.com/codedeploy/latest/userguide/reference-appspec-file.html