"""module descriptioion spelling update

Revision ID: 9e9a7f644bf6
Revises: b0f1edf6d3a2
Create Date: 2023-03-23 05:21:05.068015

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9e9a7f644bf6'
down_revision = 'b0f1edf6d3a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('module', sa.Column('description', sa.Text(), nullable=True))
    op.drop_column('module', 'desctription')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('module', sa.Column('desctription', mysql.TEXT(), nullable=True))
    op.drop_column('module', 'description')
    # ### end Alembic commands ###
