"""posts and questioon updates

Revision ID: 12c1b600443a
Revises: 5bad62b57b8d
Create Date: 2023-04-03 19:03:04.522584

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12c1b600443a'
down_revision = '5bad62b57b8d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('module_question', sa.Column('answer_comment_id', sa.String(length=20), nullable=True))
    op.create_foreign_key(None, 'module_question', 'module_question_comment', ['answer_comment_id'], ['id'])
    op.add_column('public_post', sa.Column('university_id', sa.String(length=20), nullable=True))
    op.add_column('public_post', sa.Column('university_school_id', sa.String(length=20), nullable=True))
    op.add_column('public_post', sa.Column('university_year_id', sa.String(length=20), nullable=True))
    op.create_foreign_key(None, 'public_post', 'university_school', ['university_school_id'], ['id'])
    op.create_foreign_key(None, 'public_post', 'university', ['university_id'], ['id'])
    op.create_foreign_key(None, 'public_post', 'university_year', ['university_year_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'public_post', type_='foreignkey')
    op.drop_constraint(None, 'public_post', type_='foreignkey')
    op.drop_constraint(None, 'public_post', type_='foreignkey')
    op.drop_column('public_post', 'university_year_id')
    op.drop_column('public_post', 'university_school_id')
    op.drop_column('public_post', 'university_id')
    op.drop_constraint(None, 'module_question', type_='foreignkey')
    op.drop_column('module_question', 'answer_comment_id')
    # ### end Alembic commands ###
