"""public profile

Revision ID: 23b463be6aa1
Revises: 6976dc86c948
Create Date: 2023-04-24 06:12:54.765638

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '23b463be6aa1'
down_revision = '6976dc86c948'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('public_profile',
    sa.Column('id', sa.String(length=20), nullable=False),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('date_edited', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('user_role')
    op.drop_table('module_question_edit')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('module_question_edit',
    sa.Column('id', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('date', mysql.DATETIME(), nullable=False),
    sa.Column('description', mysql.TEXT(), nullable=True),
    sa.Column('order', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_id', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('module_question_id', mysql.VARCHAR(length=20), nullable=False),
    sa.ForeignKeyConstraint(['module_question_id'], ['module_question.id'], name='module_question_edit_ibfk_1'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='module_question_edit_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('user_role',
    sa.Column('id', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=60), nullable=False),
    sa.Column('date_created', mysql.DATETIME(), nullable=False),
    sa.Column('date_edited', mysql.DATETIME(), nullable=True),
    sa.Column('user_count', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('public_profile')
    # ### end Alembic commands ###
