"""imagekit id added

Revision ID: 3b16ba579076
Revises: add592d1274e
Create Date: 2023-04-11 09:48:03.590902

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b16ba579076'
down_revision = 'add592d1274e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('image', sa.Column('imagekit_id', sa.String(length=300), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('image', 'imagekit_id')
    # ### end Alembic commands ###
