"""public profile update

Revision ID: 425a16ce9d1f
Revises: 23b463be6aa1
Create Date: 2023-04-24 08:12:20.363695

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '425a16ce9d1f'
down_revision = '23b463be6aa1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('module_question_ibfk_3', 'module_question', type_='foreignkey')
    op.drop_column('module_question', 'answer_comment_id')
    op.drop_constraint('module_question_comment_ibfk_2', 'module_question_comment', type_='foreignkey')
    op.drop_column('module_question_comment', 'parent_comment_id')
    op.drop_constraint('public_profile_ibfk_1', 'public_profile', type_='foreignkey')
    op.drop_column('public_profile', 'user_id')
    op.add_column('user', sa.Column('public_profile_id', sa.String(length=20), nullable=True))
    op.create_foreign_key(None, 'user', 'public_profile', ['public_profile_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'public_profile_id')
    op.add_column('public_profile', sa.Column('user_id', mysql.VARCHAR(length=20), nullable=False))
    op.create_foreign_key('public_profile_ibfk_1', 'public_profile', 'user', ['user_id'], ['id'])
    op.add_column('module_question_comment', sa.Column('parent_comment_id', mysql.VARCHAR(length=20), nullable=True))
    op.create_foreign_key('module_question_comment_ibfk_2', 'module_question_comment', 'module_question_comment', ['parent_comment_id'], ['id'])
    op.add_column('module_question', sa.Column('answer_comment_id', mysql.VARCHAR(length=20), nullable=True))
    op.create_foreign_key('module_question_ibfk_3', 'module_question', 'module_question_comment', ['answer_comment_id'], ['id'])
    # ### end Alembic commands ###
