"""posts added

Revision ID: 5bad62b57b8d
Revises: bb77a6ec82a7
Create Date: 2023-04-02 18:12:39.546282

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5bad62b57b8d'
down_revision = 'bb77a6ec82a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('public_post',
    sa.Column('id', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=240), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('date_edited', sa.DateTime(), nullable=True),
    sa.Column('comment_count', sa.Integer(), nullable=True),
    sa.Column('view_count', sa.Integer(), nullable=True),
    sa.Column('unique_view_count', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('public_post_comment',
    sa.Column('id', sa.String(length=20), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('date_edited', sa.DateTime(), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('sub_comment_count', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.String(length=20), nullable=False),
    sa.Column('public_post_id', sa.String(length=20), nullable=False),
    sa.Column('parent_comment_id', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['parent_comment_id'], ['public_post_comment.id'], ),
    sa.ForeignKeyConstraint(['public_post_id'], ['public_post.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('public_post_comment')
    op.drop_table('public_post')
    # ### end Alembic commands ###
