"""init3

Revision ID: 5df7b7d8d92b
Revises: 
Create Date: 2023-03-28 07:37:43.511820

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5df7b7d8d92b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('university',
    sa.Column('id', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('url', sa.String(length=300), nullable=True),
    sa.Column('date_created', sa.Date(), nullable=False),
    sa.Column('date_edited', sa.Date(), nullable=True),
    sa.Column('date_established', sa.Date(), nullable=True),
    sa.Column('first_line', sa.String(length=120), nullable=True),
    sa.Column('second_line', sa.String(length=120), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('postcode', sa.String(length=20), nullable=True),
    sa.Column('user_count', sa.Integer(), nullable=False),
    sa.Column('avg_rating', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('university_school',
    sa.Column('id', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('user_count', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.Date(), nullable=False),
    sa.Column('date_edited', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('university_year',
    sa.Column('id', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('user_count', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.Date(), nullable=False),
    sa.Column('date_edited', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_role',
    sa.Column('id', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('date_created', sa.Date(), nullable=False),
    sa.Column('date_edited', sa.Date(), nullable=True),
    sa.Column('user_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('module',
    sa.Column('id', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=240), nullable=False),
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('avg_rating', sa.Float(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('tutor', sa.String(length=240), nullable=True),
    sa.Column('date_created', sa.Date(), nullable=False),
    sa.Column('date_edited', sa.Date(), nullable=True),
    sa.Column('university_id', sa.String(length=20), nullable=True),
    sa.Column('university_school_id', sa.String(length=20), nullable=True),
    sa.Column('university_year_id', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['university_id'], ['university.id'], ),
    sa.ForeignKeyConstraint(['university_school_id'], ['university_school.id'], ),
    sa.ForeignKeyConstraint(['university_year_id'], ['university_year.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.String(length=20), nullable=False),
    sa.Column('username', sa.String(length=120), nullable=False),
    sa.Column('firstname', sa.String(length=120), nullable=True),
    sa.Column('lastname', sa.String(length=120), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=128), nullable=False),
    sa.Column('join_date', sa.DateTime(), nullable=True),
    sa.Column('university_id', sa.String(length=20), nullable=True),
    sa.Column('university_year_id', sa.String(length=20), nullable=True),
    sa.Column('university_school_id', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['university_id'], ['university.id'], ),
    sa.ForeignKeyConstraint(['university_school_id'], ['university_school.id'], ),
    sa.ForeignKeyConstraint(['university_year_id'], ['university_year.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('module_review',
    sa.Column('id', sa.String(length=20), nullable=False),
    sa.Column('date_sent', sa.Date(), nullable=False),
    sa.Column('date_edited', sa.Date(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=240), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('user_id', sa.String(length=20), nullable=False),
    sa.Column('module_id', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['module_id'], ['module.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_role_link',
    sa.Column('user', sa.String(length=20), nullable=False),
    sa.Column('user_role', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['user'], ['user.id'], ),
    sa.ForeignKeyConstraint(['user_role'], ['user_role.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_role_link')
    op.drop_table('module_review')
    op.drop_table('user')
    op.drop_table('module')
    op.drop_table('user_role')
    op.drop_table('university_year')
    op.drop_table('university_school')
    op.drop_table('university')
    # ### end Alembic commands ###
