"""user role

Revision ID: 6976dc86c948
Revises: dc3e1fbce6e7
Create Date: 2023-04-16 16:52:39.981724

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6976dc86c948'
down_revision = 'dc3e1fbce6e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_role_link')
    op.add_column('user', sa.Column('is_admin', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_admin')
    op.create_table('user_role_link',
    sa.Column('user', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('user_role', mysql.VARCHAR(length=20), nullable=False),
    sa.ForeignKeyConstraint(['user'], ['user.id'], name='user_role_link_ibfk_1'),
    sa.ForeignKeyConstraint(['user_role'], ['user_role.id'], name='user_role_link_ibfk_2'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
