"""message stuff

Revision ID: 8ba28f56e0fe
Revises: a882ad846863
Create Date: 2023-04-12 08:53:59.848621

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ba28f56e0fe'
down_revision = 'a882ad846863'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message_thread',
    sa.Column('id', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=240), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.Column('date_last_message', sa.DateTime(), nullable=True),
    sa.Column('member_count', sa.Integer(), nullable=False),
    sa.Column('message_count', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('message',
    sa.Column('id', sa.String(length=20), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('date_sent', sa.DateTime(), nullable=False),
    sa.Column('date_edited', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.String(length=20), nullable=False),
    sa.Column('message_thread_id', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['message_thread_id'], ['message_thread.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_message_thread_link',
    sa.Column('user', sa.String(length=20), nullable=False),
    sa.Column('message_thread', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['message_thread'], ['message_thread.id'], ),
    sa.ForeignKeyConstraint(['user'], ['user.id'], )
    )
    op.add_column('module', sa.Column('message_thread_id', sa.String(length=20), nullable=True))
    op.create_foreign_key(None, 'module', 'message_thread', ['message_thread_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'module', type_='foreignkey')
    op.drop_column('module', 'message_thread_id')
    op.drop_table('user_message_thread_link')
    op.drop_table('message')
    op.drop_table('message_thread')
    # ### end Alembic commands ###
