"""imfile type added

Revision ID: a882ad846863
Revises: 19627a153a42
Create Date: 2023-04-11 11:44:22.596215

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a882ad846863'
down_revision = '19627a153a42'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document', sa.Column('file_type', sa.String(length=20), nullable=True))
    op.add_column('image', sa.Column('file_type', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('image', 'file_type')
    op.drop_column('document', 'file_type')
    # ### end Alembic commands ###
