"""module resource e date change

Revision ID: add592d1274e
Revises: 2f68320382e0
Create Date: 2023-04-11 05:02:03.975362

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'add592d1274e'
down_revision = '2f68320382e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document', sa.Column('date', sa.DateTime(), nullable=False))
    op.drop_column('document', 'date_added')
    op.add_column('image', sa.Column('date', sa.DateTime(), nullable=False))
    op.drop_column('image', 'date_added')
    op.add_column('module_resource', sa.Column('date', sa.DateTime(), nullable=False))
    op.drop_column('module_resource', 'date_created')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('module_resource', sa.Column('date_created', mysql.DATETIME(), nullable=False))
    op.drop_column('module_resource', 'date')
    op.add_column('image', sa.Column('date_added', mysql.DATETIME(), nullable=False))
    op.drop_column('image', 'date')
    op.add_column('document', sa.Column('date_added', mysql.DATETIME(), nullable=False))
    op.drop_column('document', 'date')
    # ### end Alembic commands ###
