"""question comments fixed

Revision ID: bb77a6ec82a7
Revises: 23a93ef40c71
Create Date: 2023-04-02 05:56:11.677226

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bb77a6ec82a7'
down_revision = '23a93ef40c71'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('module_question_comment', 'message',
               existing_type=mysql.TEXT(),
               nullable=False)
    op.alter_column('module_question_comment', 'parent_comment_id',
               existing_type=mysql.VARCHAR(length=20),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('module_question_comment', 'parent_comment_id',
               existing_type=mysql.VARCHAR(length=20),
               nullable=False)
    op.alter_column('module_question_comment', 'message',
               existing_type=mysql.TEXT(),
               nullable=True)
    # ### end Alembic commands ###
