"""messagethread changes

Revision ID: dc3e1fbce6e7
Revises: 8ba28f56e0fe
Create Date: 2023-04-12 11:25:12.148183

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'dc3e1fbce6e7'
down_revision = '8ba28f56e0fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message_thread', sa.Column('date', sa.DateTime(), nullable=False))
    op.alter_column('message_thread', 'user_id',
               existing_type=mysql.VARCHAR(length=20),
               nullable=True)
    op.drop_column('message_thread', 'date_created')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message_thread', sa.Column('date_created', mysql.DATETIME(), nullable=False))
    op.alter_column('message_thread', 'user_id',
               existing_type=mysql.VARCHAR(length=20),
               nullable=False)
    op.drop_column('message_thread', 'date')
    # ### end Alembic commands ###
